import { useEffect, useState, useRef } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import endingPrompt from '../assets/05_ending.md?raw'
import { PageHeader } from '../components/PageHeader'
import { characterClasses } from '../data/classes'
import {
  type SelectedItem,
  type StoryScene,
  type StorySceneState,
} from '../lib/character-storage'
import { postChatCompletion } from '../lib/api-client'
import { useGameStore } from '../store/game-store'
import { formatTextWithLineBreaks } from '../lib/text-utils'

function getAbilityRows(scores: Record<string, number>) {
  return [
    ['筋力', scores.strength],
    ['敏捷', scores.dexterity],
    ['耐久', scores.constitution],
    ['知力', scores.intelligence],
    ['判断力', scores.wisdom],
    ['魅力', scores.charisma],
  ] as const
}

function getSceneResolution(
  sceneState: StorySceneState,
  abilityScores: Record<string, number>,
) {
  if (!sceneState.judgeResult) {
    return null
  }

  if (!sceneState.judgeResult.needs_roll) {
    return {
      result: '判定不要',
      summary: sceneState.judgeResult.message,
    }
  }

  if (sceneState.diceRoll === null || sceneState.judgeResult.difficulty === null) {
    return {
      result: null,
      summary: sceneState.judgeResult.message,
    }
  }

  const ability = sceneState.judgeResult.ability
  const score =
    ability === 'strength'
      ? abilityScores.strength
      : ability === 'dexterity'
        ? abilityScores.dexterity
        : ability === 'constitution'
          ? abilityScores.constitution
          : ability === 'intelligence'
            ? abilityScores.intelligence
            : ability === 'wisdom'
              ? abilityScores.wisdom
              : ability === 'charisma'
                ? abilityScores.charisma
                : 10
  const modifier = Math.floor((score - 10) / 2)
  const total = sceneState.diceRoll + modifier

  return {
    result: total >= sceneState.judgeResult.difficulty ? '成功' : '失敗',
    summary: sceneState.judgeResult.message,
  }
}

export function EndingPage() {
  const navigate = useNavigate()
  const selectedClassId = useGameStore((state) => state.selectedClassId)
  const abilityScores = useGameStore((state) => state.abilityScores)
  const backgroundData = useGameStore((state) => state.backgroundData)
  const sceneStates = useGameStore((state) => state.sceneStates)
  const resetGame = useGameStore((state) => state.resetGame)
  const getSceneState = useGameStore((state) => state.getSceneState)
  const setStories = useGameStore((state) => state.setStories)
  const setSceneState = useGameStore((state) => state.setSceneState)
  const selectedJob = characterClasses.find((job) => job.id === selectedClassId)
  const abilityRows = getAbilityRows(abilityScores)
  const endingSceneNumber = 6
  const previousSceneNumber = endingSceneNumber - 1
  const previousSceneState = getSceneState(previousSceneNumber)
  const [generatedEnding, setGeneratedEnding] = useState<StoryScene | null>(() => {
    return getSceneState(endingSceneNumber).scene
  })
  const [errorMessage, setErrorMessage] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const isGeneratingRef = useRef<number | null>(null)
  const autoGeneratedEndingNumbersRef = useRef<Set<number>>(new Set())
  const shouldRedirectToBackground = !selectedJob || !backgroundData

  useEffect(() => {
    document.title = generatedEnding?.scene_title
      ? `エンディング：${generatedEnding.scene_title} | TRPG`
      : 'エンディング | TRPG'
  }, [generatedEnding?.scene_title])

  useEffect(() => {
    setGeneratedEnding(getSceneState(endingSceneNumber).scene)
  }, [endingSceneNumber, getSceneState, sceneStates])

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'auto' })
  }, [endingSceneNumber])

  useEffect(() => {
    if (shouldRedirectToBackground) {
      return
    }

    const storedEndingState = getSceneState(endingSceneNumber)

    if (
      generatedEnding ||
      storedEndingState.scene ||
      isLoading ||
      isGeneratingRef.current === endingSceneNumber ||
      autoGeneratedEndingNumbersRef.current.has(endingSceneNumber)
    ) {
      return
    }

    autoGeneratedEndingNumbersRef.current.add(endingSceneNumber)
    void (async () => {
      if (isGeneratingRef.current === endingSceneNumber) return
      isGeneratingRef.current = endingSceneNumber
      if (!selectedJob || !backgroundData || !previousSceneState.scene) {
        setErrorMessage('エンディング生成に必要な情報が不足しています。')
        return
      }

      setIsLoading(true)
      setErrorMessage('')

      const storyScenes = sceneStates
        .filter((sceneState) => sceneState.sceneNumber <= previousSceneNumber)
        .map((sceneState) => ({
          sceneNumber: sceneState.sceneNumber,
          scene: sceneState.scene,
          items: sceneState.items,
          playerAction: sceneState.playerAction,
          activeItemIds: sceneState.activeItemIds,
          resolution: getSceneResolution(sceneState, abilityScores),
        }))

      const userPrompt = [
        '# current_scene_number',
        JSON.stringify(endingSceneNumber, null, 2),
        '',
        '# background',
        JSON.stringify(
          {
            title: backgroundData.intro_title,
            text: backgroundData.intro_text,
          },
          null,
          2,
        ),
        '',
        '# character',
        JSON.stringify(
          {
            class: selectedJob.name,
            abilityScores: Object.fromEntries(abilityRows),
          },
          null,
          2,
        ),
        '',
        '# items',
        JSON.stringify(previousSceneState.items, null, 2),
        '',
        '# story_history',
        JSON.stringify(storyScenes, null, 2),
        '',
        '# previous_scene',
        JSON.stringify(
          {
            sceneNumber: previousSceneState.sceneNumber,
            scene: previousSceneState.scene,
            items: previousSceneState.items,
            playerAction: previousSceneState.playerAction,
            activeItemIds: previousSceneState.activeItemIds,
            resolution: getSceneResolution(previousSceneState, abilityScores),
          },
          null,
          2,
        ),
      ].join('\n')

      try {
        const parsed = await postChatCompletion<{ scene_title: string; scene_text: string; items: SelectedItem[] }>({
          messages: [
            { role: 'system', content: endingPrompt },
            { role: 'user', content: userPrompt },
          ],
          tools: [
            {
              type: 'function',
              function: {
                name: 'generate_scene',
                description: 'TRPGのエンディングシーンを生成します。',
                parameters: {
                  type: 'object',
                  properties: {
                    scene_title: { type: 'string' },
                    scene_text: { type: 'string' },
                    items: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          id: { type: 'string' },
                          name: { type: 'string' },
                          description: { type: 'string' },
                          category: { type: 'string' },
                        },
                        required: ['id', 'name', 'description', 'category'],
                      },
                    },
                  },
                  required: ['scene_title', 'scene_text', 'items'],
                },
              },
            },
          ],
          tool_choice: { type: 'function', function: { name: 'generate_scene' } },
        })

        const nextEnding = {
          scene_title: parsed.scene_title,
          scene_text: parsed.scene_text,
        }

        setGeneratedEnding(nextEnding)
        const nextEndingState = {
          ...getSceneState(endingSceneNumber),
          sceneNumber: endingSceneNumber,
          scene: nextEnding,
          items: parsed.items,
        }
        setSceneState(nextEndingState)
        const nextStories = sceneStates
          .filter((sceneState) => sceneState.sceneNumber <= endingSceneNumber)
          .map((sceneState) =>
            sceneState.sceneNumber === endingSceneNumber ? nextEndingState.scene : sceneState.scene,
          )
          .filter((scene): scene is StoryScene => scene !== null)
        setStories(nextStories)
      } catch (error) {
        setErrorMessage(
          error instanceof Error ? error.message : 'エンディング生成中に不明なエラーが発生しました。',
        )
      } finally {
        setIsLoading(false)
        isGeneratingRef.current = null
      }
    })()
  }, [
    backgroundData?.intro_text,
    backgroundData?.intro_title,
    abilityScores.charisma,
    abilityScores.constitution,
    abilityScores.dexterity,
    abilityScores.intelligence,
    abilityScores.strength,
    abilityScores.wisdom,
    endingSceneNumber,
    generatedEnding,
    getSceneState,
    isLoading,
    previousSceneNumber,
    sceneStates,
    selectedJob?.name,
    setSceneState,
    setStories,
    shouldRedirectToBackground,
  ])

  const handleGenerateEnding = async () => {
    if (isGeneratingRef.current === endingSceneNumber) return
    isGeneratingRef.current = endingSceneNumber
    if (!selectedJob || !backgroundData || !previousSceneState.scene) {
      setErrorMessage('エンディング生成に必要な情報が不足しています。')
      return
    }

    setIsLoading(true)
    setErrorMessage('')

    const storyScenes = sceneStates
      .filter((sceneState) => sceneState.sceneNumber <= previousSceneNumber)
      .map((sceneState) => ({
        sceneNumber: sceneState.sceneNumber,
        scene: sceneState.scene,
        items: sceneState.items,
        playerAction: sceneState.playerAction,
        activeItemIds: sceneState.activeItemIds,
        resolution: getSceneResolution(sceneState, abilityScores),
      }))

    const userPrompt = [
      '# current_scene_number',
      JSON.stringify(endingSceneNumber, null, 2),
      '',
      '# background',
      JSON.stringify(
        {
          title: backgroundData.intro_title,
          text: backgroundData.intro_text,
        },
        null,
        2,
      ),
      '',
      '# character',
      JSON.stringify(
        {
          class: selectedJob.name,
          abilityScores: Object.fromEntries(abilityRows),
        },
        null,
        2,
      ),
      '',
      '# items',
      JSON.stringify(previousSceneState.items, null, 2),
      '',
      '# story_history',
      JSON.stringify(storyScenes, null, 2),
      '',
      '# previous_scene',
      JSON.stringify(
        {
          sceneNumber: previousSceneState.sceneNumber,
          scene: previousSceneState.scene,
          items: previousSceneState.items,
          playerAction: previousSceneState.playerAction,
          activeItemIds: previousSceneState.activeItemIds,
          resolution: getSceneResolution(previousSceneState, abilityScores),
        },
        null,
        2,
      ),
    ].join('\n')

    try {
      const parsed = await postChatCompletion<{ scene_title: string; scene_text: string; items: SelectedItem[] }>({
        messages: [
          { role: 'system', content: endingPrompt },
          { role: 'user', content: userPrompt },
        ],
        tools: [
          {
            type: 'function',
            function: {
              name: 'generate_scene',
              description: 'TRPGのエンディングシーンを生成します。',
              parameters: {
                type: 'object',
                properties: {
                  scene_title: { type: 'string' },
                  scene_text: { type: 'string' },
                  items: {
                    type: 'array',
                    items: {
                      type: 'object',
                      properties: {
                        id: { type: 'string' },
                        name: { type: 'string' },
                        description: { type: 'string' },
                        category: { type: 'string' },
                      },
                      required: ['id', 'name', 'description', 'category'],
                    },
                  },
                },
                required: ['scene_title', 'scene_text', 'items'],
              },
            },
          },
        ],
        tool_choice: { type: 'function', function: { name: 'generate_scene' } },
      })

      const nextEnding = {
        scene_title: parsed.scene_title,
        scene_text: parsed.scene_text,
      }

      setGeneratedEnding(nextEnding)
      const nextEndingState = {
        ...getSceneState(endingSceneNumber),
        sceneNumber: endingSceneNumber,
        scene: nextEnding,
        items: parsed.items,
      }
      setSceneState(nextEndingState)
      const nextStories = sceneStates
        .filter((sceneState) => sceneState.sceneNumber <= endingSceneNumber)
        .map((sceneState) =>
          sceneState.sceneNumber === endingSceneNumber ? nextEndingState.scene : sceneState.scene,
        )
        .filter((scene): scene is StoryScene => scene !== null)
      setStories(nextStories)
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : 'エンディング生成中に不明なエラーが発生しました。',
      )
    } finally {
      setIsLoading(false)
      isGeneratingRef.current = null
    }
  }

  const handleBackToClimax = () => {
    navigate(`/story?scene=${previousSceneNumber}`)
  }

  const handleRestart = () => {
    resetGame()
    navigate('/', { replace: true })
  }

  if (shouldRedirectToBackground) {
    return <Navigate to="/background" replace />
  }

  return (
    <main className="page-shell px-4" data-theme="light">
      <PageHeader
        title={generatedEnding?.scene_title ? `エンディング：${generatedEnding.scene_title}` : 'エンディング'}
        backAction={{ label: '戻る', onClick: handleBackToClimax, variant: 'outline' }}
        restartAction={{ label: '最初から', onClick: handleRestart, variant: 'error' }}
      />
      <section className="page-panel w-full max-w-[980px] p-5">
        <div className="mx-auto max-w-[760px]">
          {errorMessage ? <p className="alert alert-error text-base">{errorMessage}</p> : null}
          <section className="card border border-base-300 bg-base-200/70">
            <div className="card-body p-6">
              <p className="text-sm uppercase tracking-[0.28em] text-base-content/55">Ending</p>
              {generatedEnding ? (
                <>
                  <h1 className="mt-3 font-[var(--heading-font)] text-4xl text-neutral">
                    {generatedEnding.scene_title}
                  </h1>
                  <p className="mt-6 whitespace-pre-wrap text-lg leading-9 text-base-content">
                    {formatTextWithLineBreaks(generatedEnding.scene_text)}
                  </p>
                </>
              ) : (
                <p className="mt-4 text-base leading-8 text-base-content">
                  エンディングを生成しています。しばらく待つと、旅の結末が表示されます。
                </p>
              )}
            </div>
          </section>
          <div className="mt-5 flex justify-end">
            <button
              type="button"
              className="btn btn-primary disabled:opacity-50"
              onClick={handleGenerateEnding}
              disabled={isLoading}
            >
              {isLoading ? '生成中...' : 'エンディング再生成'}
            </button>
          </div>
        </div>
      </section>
    </main>
  )
}
