import { useEffect, useState } from 'react'
import { Navigate, useNavigate, useSearchParams } from 'react-router-dom'
import gmPrompt from '../assets/02_gm.md?raw'
import continueGmPrompt from '../assets/04_gm.md?raw'
import judgePrompt from '../assets/03_judge.md?raw'
import { PageHeader } from '../components/PageHeader'
import { characterClasses } from '../data/classes'
import {
  clearStoredStorySceneStatesAfter,
  clearAllStoredGameData,
  createEmptyStorySceneState,
  getStoredActiveItemIds,
  getStoredBackgroundData,
  getStoredAbilityScores,
  getStoredClassId,
  getStoredDiceRoll,
  getStoredJudgeResult,
  getStoredPlayerAction,
  getStoredSelectedItems,
  getStoredStoryScene,
  getStoredStorySceneState,
  getStoredStorySceneStates,
  setStoredActiveItemIds,
  setStoredDiceRoll,
  setStoredJudgeResult,
  setStoredPlayerAction,
  setStoredStoryScene,
  setStoredStorySceneState,
  setStoredStories,
  type JudgeResult,
  type SelectedItem,
  type StoryScene,
  type StorySceneState,
} from '../lib/character-storage'
import { postChatCompletion } from '../lib/api-client'
const IS_DEV = import.meta.env.DEV

const abilityLabels = {
  strength: '筋力',
  dexterity: '敏捷',
  constitution: '耐久',
  intelligence: '知力',
  wisdom: '判断力',
  charisma: '魅力',
} as const

function getAbilityRows() {
  const scores = getStoredAbilityScores()

  return [
    ['筋力', scores.strength],
    ['敏捷', scores.dexterity],
    ['耐久', scores.constitution],
    ['知力', scores.intelligence],
    ['判断力', scores.wisdom],
    ['魅力', scores.charisma],
  ] as const
}

function extractTextContent(content: unknown) {
  if (typeof content === 'string') {
    return content
  }

  if (Array.isArray(content)) {
    return content
      .map((item) => {
        if (typeof item === 'string') {
          return item
        }

        if (
          typeof item === 'object' &&
          item !== null &&
          'type' in item &&
          item.type === 'text' &&
          'text' in item &&
          typeof item.text === 'string'
        ) {
          return item.text
        }

        return ''
      })
      .join('\n')
      .trim()
  }

  return ''
}

function getAbilityModifier(ability: string | null) {
  const scores = getStoredAbilityScores()

  switch (ability) {
    case 'strength':
      return Math.floor((scores.strength - 10) / 2)
    case 'dexterity':
      return Math.floor((scores.dexterity - 10) / 2)
    case 'constitution':
      return Math.floor((scores.constitution - 10) / 2)
    case 'intelligence':
      return Math.floor((scores.intelligence - 10) / 2)
    case 'wisdom':
      return Math.floor((scores.wisdom - 10) / 2)
    case 'charisma':
      return Math.floor((scores.charisma - 10) / 2)
    default:
      return 0
  }
}

function getSceneOutcome(sceneState: StorySceneState) {
  if (!sceneState.judgeResult?.needs_roll) {
    return sceneState.judgeResult ? '判定不要' : null
  }

  if (sceneState.diceRoll === null || sceneState.judgeResult.difficulty === null) {
    return null
  }

  const modifier = getAbilityModifier(sceneState.judgeResult.ability)
  const total = sceneState.diceRoll + modifier

  return total >= sceneState.judgeResult.difficulty ? '成功' : '失敗'
}

function getSceneResolution(sceneState: StorySceneState) {
  if (!sceneState.judgeResult) {
    return null
  }

  const outcome = getSceneOutcome(sceneState)

  return {
    result: outcome,
    summary: sceneState.judgeResult.message,
  }
}

export function StoryPage() {
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()
  const selectedClassId = getStoredClassId()
  const selectedJob = characterClasses.find((job) => job.id === selectedClassId)
  const backgroundData = getStoredBackgroundData()
  const abilityRows = getAbilityRows()
  const sceneFromSearchParams = Number(searchParams.get('scene') ?? searchParams.get('turn') ?? '1')
  const currentSceneNumber =
    Number.isInteger(sceneFromSearchParams) && sceneFromSearchParams > 0 ? sceneFromSearchParams : 1
  const [generatedScene, setGeneratedScene] = useState<StoryScene | null>(null)
  const [judgeResult, setJudgeResult] = useState<JudgeResult | null>(null)
  const [diceRoll, setDiceRoll] = useState<number | null>(null)
  const [rollingValue, setRollingValue] = useState<number>(1)
  const [sceneItems, setSceneItems] = useState<SelectedItem[]>([])
  const [activeItemIds, setActiveItemIdsState] = useState<string[]>([])
  const [playerAction, setPlayerActionState] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [isSceneLoading, setIsSceneLoading] = useState(false)
  const [isJudgeLoading, setIsJudgeLoading] = useState(false)
  const [autoGeneratedSceneNumbers, setAutoGeneratedSceneNumbers] = useState<number[]>([])
  const currentSceneState = getStoredStorySceneState(currentSceneNumber)
  const maxHp = currentSceneState.maxHp
  const currentHp = currentSceneState.currentHp
  const hpRatio = maxHp > 0 ? Math.max(0, Math.min(100, (currentHp / maxHp) * 100)) : 0

  if (!selectedJob || !backgroundData) {
    return <Navigate to="/background" replace />
  }

  const availableActiveItemIds = activeItemIds.filter((itemId) =>
    sceneItems.some((item) => item.id === itemId),
  )
  const activeItems = sceneItems.filter((item) =>
    availableActiveItemIds.includes(item.id),
  )
  const isRolling = judgeResult?.needs_roll === true && diceRoll === null

  useEffect(() => {
    if (searchParams.get('scene') === String(currentSceneNumber)) {
      return
    }

    setSearchParams({ scene: String(currentSceneNumber) }, { replace: true })
  }, [currentSceneNumber, searchParams, setSearchParams])

  useEffect(() => {
    let storedSceneState = getStoredStorySceneState(currentSceneNumber)

    if (
      currentSceneNumber === 1 &&
      storedSceneState.scene === null &&
      storedSceneState.activeItemIds.length === 0 &&
      storedSceneState.playerAction === '' &&
      storedSceneState.judgeResult === null &&
      storedSceneState.diceRoll === null
    ) {
      const previousSceneState = getStoredStorySceneState(0)
      const migratedSceneState = {
        sceneNumber: 1,
        scene: getStoredStoryScene(),
        maxHp: previousSceneState.maxHp,
        currentHp: previousSceneState.currentHp,
        items: getStoredSelectedItems(),
        activeItemIds: getStoredActiveItemIds(),
        playerAction: getStoredPlayerAction(),
        judgeResult: getStoredJudgeResult(),
        diceRoll: getStoredDiceRoll(),
      }

      const hasLegacyState =
        migratedSceneState.scene !== null ||
        migratedSceneState.items.length > 0 ||
        migratedSceneState.activeItemIds.length > 0 ||
        migratedSceneState.playerAction !== '' ||
        migratedSceneState.judgeResult !== null ||
        migratedSceneState.diceRoll !== null

      if (hasLegacyState) {
        setStoredStorySceneState(migratedSceneState)
        storedSceneState = migratedSceneState
      }
    }

    if (storedSceneState.items.length === 0 && currentSceneNumber > 0) {
      const previousSceneState = getStoredStorySceneState(currentSceneNumber - 1)

      if (
        previousSceneState.items.length > 0 ||
        previousSceneState.maxHp > 0 ||
        previousSceneState.currentHp > 0
      ) {
        storedSceneState = {
          ...storedSceneState,
          maxHp: previousSceneState.maxHp,
          currentHp: previousSceneState.currentHp,
          items: previousSceneState.items,
        }
        setStoredStorySceneState(storedSceneState)
      }
    }

    setGeneratedScene(storedSceneState.scene)
    setSceneItems(storedSceneState.items)
    setJudgeResult(storedSceneState.judgeResult)
    setDiceRoll(storedSceneState.diceRoll)
    setActiveItemIdsState(storedSceneState.activeItemIds)
    setPlayerActionState(storedSceneState.playerAction)
    setErrorMessage('')
  }, [currentSceneNumber])

  useEffect(() => {
    document.title = generatedScene?.scene_title
      ? `シーン${currentSceneNumber}：${generatedScene.scene_title} | TRPG`
      : `シーン${currentSceneNumber} | TRPG`
  }, [currentSceneNumber, generatedScene?.scene_title])

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'auto' })
  }, [currentSceneNumber])

  useEffect(() => {
    const storedSceneState = getStoredStorySceneState(currentSceneNumber)

    if (
      generatedScene ||
      storedSceneState.scene ||
      isSceneLoading ||
      autoGeneratedSceneNumbers.includes(currentSceneNumber)
    ) {
      return
    }

    setAutoGeneratedSceneNumbers((current) => [...current, currentSceneNumber])
    void handleGenerateScene()
  }, [autoGeneratedSceneNumbers, currentSceneNumber, generatedScene, isSceneLoading])

  useEffect(() => {
    if (!isRolling) {
      return
    }

    const intervalId = window.setInterval(() => {
      setRollingValue(Math.floor(Math.random() * 20) + 1)
    }, 80)

    return () => {
      window.clearInterval(intervalId)
    }
  }, [isRolling])

  const persistSceneState = (updater: (sceneState: StorySceneState) => StorySceneState) => {
    const currentSceneState = getStoredStorySceneState(currentSceneNumber)
    setStoredStorySceneState(updater(currentSceneState))
  }

  const persistCurrentSceneState = () => {
    setStoredStorySceneState({
      sceneNumber: currentSceneNumber,
      scene: generatedScene,
      maxHp: currentSceneState.maxHp,
      currentHp: currentSceneState.currentHp,
      items: sceneItems,
      activeItemIds: availableActiveItemIds,
      playerAction,
      judgeResult,
      diceRoll,
    })
  }

  const clearFutureScenes = () => {
    clearStoredStorySceneStatesAfter(currentSceneNumber)

    const nextStories = getStoredStorySceneStates()
      .filter((sceneState) => sceneState.sceneNumber <= currentSceneNumber)
      .map((sceneState) => sceneState.scene)
      .filter((scene): scene is StoryScene => scene !== null)

    setStoredStories(nextStories)
  }

  const setPlayerAction = (value: string) => {
    setPlayerActionState(value)
    setStoredPlayerAction(value)
    persistSceneState((sceneState) => ({
      ...sceneState,
      playerAction: value,
    }))
  }

  const handleToggleActiveItem = (itemId: string) => {
    const nextIds = availableActiveItemIds.includes(itemId)
      ? availableActiveItemIds.filter((currentItemId) => currentItemId !== itemId)
      : [...availableActiveItemIds, itemId]

    setActiveItemIdsState(nextIds)
    setStoredActiveItemIds(nextIds)
    persistSceneState((sceneState) => ({
      ...sceneState,
      activeItemIds: nextIds,
    }))
  }

  const handleGenerateScene = async () => {
    setIsSceneLoading(true)
    setErrorMessage('')

    const storyScenes = getStoredStorySceneStates()
      .filter((sceneState) => sceneState.sceneNumber < currentSceneNumber)
      .map((sceneState) => ({
        sceneNumber: sceneState.sceneNumber,
        scene: sceneState.scene,
        items: sceneState.items,
        playerAction: sceneState.playerAction,
        activeItemIds: sceneState.activeItemIds,
        resolution: getSceneResolution(sceneState),
      }))
    const previousScene = storyScenes.at(-1) ?? null
    const systemPrompt = currentSceneNumber === 1 ? gmPrompt : continueGmPrompt

    const userPrompt = [
      '# current_scene_number',
      JSON.stringify(currentSceneNumber, null, 2),
      '',
      '# background',
      JSON.stringify(
        {
          title: backgroundData.intro_title,
          text: backgroundData.intro_text,
        },
        null,
        2,
      ),
      '',
      '# character',
      JSON.stringify(
        {
          class: selectedJob.name,
          abilityScores: Object.fromEntries(abilityRows),
        },
        null,
        2,
      ),
      '',
      '# items',
      JSON.stringify(sceneItems, null, 2),
      '',
      '# story_history',
      JSON.stringify(storyScenes, null, 2),
    ].join('\n')

    const continuePrompt =
      currentSceneNumber === 1
        ? userPrompt
        : [
            userPrompt,
            '',
            '# previous_scene',
            JSON.stringify(previousScene, null, 2),
          ].join('\n')

    try {
      const data = await postChatCompletion({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: continuePrompt },
        ],
        response_format: {
          type: 'json_schema',
          json_schema: {
            name: 'story_scene_response',
            strict: true,
            schema: {
              type: 'object',
              additionalProperties: false,
              properties: {
                scene_title: { type: 'string' },
                scene_text: { type: 'string' },
                is_ending: { type: 'boolean' },
                next_is_ending: { type: 'boolean' },
                items: {
                  type: 'array',
                  items: {
                    type: 'object',
                    additionalProperties: false,
                    properties: {
                      id: { type: 'string' },
                      name: { type: 'string' },
                      description: { type: 'string' },
                      category: { type: 'string' },
                    },
                    required: ['id', 'name', 'description', 'category'],
                  },
                },
              },
              required: ['scene_title', 'scene_text', 'is_ending', 'next_is_ending', 'items'],
            },
          },
        },
      })

      const content = extractTextContent(data.choices?.[0]?.message?.content)

      if (!content) {
        throw new Error('生成結果が空でした。')
      }

      const parsed = JSON.parse(content) as StoryScene & { items: SelectedItem[] }
      clearFutureScenes()
      const nextActiveItemIds = availableActiveItemIds.filter((itemId) =>
        parsed.items.some((item) => item.id === itemId),
      )
      const nextScene = {
        scene_title: parsed.scene_title,
        scene_text: parsed.scene_text,
        is_ending: parsed.is_ending,
        next_is_ending: parsed.next_is_ending,
      }
      setGeneratedScene(nextScene)
      setSceneItems(parsed.items)
      setActiveItemIdsState(nextActiveItemIds)
      setStoredActiveItemIds(nextActiveItemIds)
      setStoredStoryScene(nextScene)
      const nextStories = getStoredStorySceneStates()
        .filter((sceneState) => sceneState.sceneNumber <= currentSceneNumber)
        .map((sceneState) =>
          sceneState.sceneNumber === currentSceneNumber ? nextScene : sceneState.scene,
        )
        .filter((scene): scene is StoryScene => scene !== null)

      setStoredStories(nextStories)
      persistSceneState((sceneState) => ({
        ...sceneState,
        scene: nextScene,
        items: parsed.items,
        activeItemIds: nextActiveItemIds,
      }))
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : 'シーン生成中に不明なエラーが発生しました。',
      )
    } finally {
      setIsSceneLoading(false)
    }
  }

  const handleConfirmAction = async () => {
    const trimmedAction = playerAction.trim()

    if (!trimmedAction) {
      setErrorMessage('ユーザー行動を入力してください。')
      return
    }

    try {
      setIsJudgeLoading(true)
      setErrorMessage('')

      const storyScenes = getStoredStorySceneStates()
        .filter((sceneState) => sceneState.sceneNumber <= currentSceneNumber)
        .map((sceneState) => ({
          sceneNumber: sceneState.sceneNumber,
          scene: sceneState.scene,
          items: sceneState.items,
          playerAction: sceneState.playerAction,
          activeItemIds: sceneState.activeItemIds,
          resolution: getSceneResolution(sceneState),
        }))

      const userPrompt = [
        '# background',
        JSON.stringify(
          {
            title: backgroundData.intro_title,
            text: backgroundData.intro_text,
          },
          null,
          2,
        ),
        '',
        '# character',
        JSON.stringify(
          {
            class: selectedJob.name,
            abilityScores: Object.fromEntries(abilityRows),
          },
          null,
          2,
        ),
        '',
        '# owned_items',
        JSON.stringify(sceneItems, null, 2),
        '',
        '# active_items',
        JSON.stringify(activeItems, null, 2),
        '',
        '# story_history',
        JSON.stringify(storyScenes, null, 2),
        '',
        '# current_scene',
        JSON.stringify(
          {
            sceneNumber: currentSceneNumber,
            scene: generatedScene,
            playerAction: trimmedAction,
            activeItemIds: availableActiveItemIds,
          },
          null,
          2,
        ),
      ].join('\n')

      const data = await postChatCompletion({
        messages: [
          { role: 'system', content: judgePrompt },
          { role: 'user', content: userPrompt },
        ],
        response_format: {
          type: 'json_schema',
          json_schema: {
            name: 'judge_scene_response',
            strict: true,
            schema: {
              type: 'object',
              additionalProperties: false,
              properties: {
                needs_roll: { type: 'boolean' },
                ability: {
                  anyOf: [
                    {
                      type: 'string',
                      enum: [
                        'strength',
                        'dexterity',
                        'constitution',
                        'intelligence',
                        'wisdom',
                        'charisma',
                      ],
                    },
                    { type: 'null' },
                  ],
                },
                skill: {
                  anyOf: [{ type: 'string' }, { type: 'null' }],
                },
                difficulty: {
                  anyOf: [{ type: 'integer' }, { type: 'null' }],
                },
                message: { type: 'string' },
              },
              required: ['needs_roll', 'ability', 'skill', 'difficulty', 'message'],
            },
          },
        },
      })

      const content = extractTextContent(data.choices?.[0]?.message?.content)

      if (!content) {
        throw new Error('判定結果が空でした。')
      }

      const parsed = JSON.parse(content) as JudgeResult
      clearFutureScenes()
      setJudgeResult(parsed)
      setStoredJudgeResult(parsed)
      setDiceRoll(null)
      setStoredDiceRoll(null)
      setRollingValue(Math.floor(Math.random() * 20) + 1)
      persistSceneState((sceneState) => ({
        ...sceneState,
        items: sceneItems,
        judgeResult: parsed,
        diceRoll: null,
        playerAction: trimmedAction,
        activeItemIds: availableActiveItemIds,
      }))
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : '行動確定中に不明なエラーが発生しました。',
      )
    } finally {
      setIsJudgeLoading(false)
    }
  }

  const handleRollDice = () => {
    if (!isRolling) {
      return
    }

    setDiceRoll(rollingValue)
    setStoredDiceRoll(rollingValue)
    persistSceneState((sceneState) => ({
      ...sceneState,
      diceRoll: rollingValue,
    }))
  }

  const handleRerollDice = () => {
    if (!judgeResult?.needs_roll || diceRoll === null || !IS_DEV) {
      return
    }

    const rerolledValue = Math.floor(Math.random() * 20) + 1
    setDiceRoll(rerolledValue)
    setStoredDiceRoll(rerolledValue)
    persistSceneState((sceneState) => ({
      ...sceneState,
      diceRoll: rerolledValue,
    }))
  }

  const handleNextScene = () => {
    persistCurrentSceneState()
    setJudgeResult(null)
    setStoredJudgeResult(null)
    setDiceRoll(null)
    setStoredDiceRoll(null)
    const nextSceneNumber = currentSceneNumber + 1

    if (generatedScene?.next_is_ending) {
      navigate(`/ending?scene=${nextSceneNumber}`)
      return
    }

    const nextSceneState = getStoredStorySceneState(nextSceneNumber)

    if (
      nextSceneState.scene === null &&
      nextSceneState.items.length === 0 &&
      nextSceneState.activeItemIds.length === 0 &&
      nextSceneState.playerAction === '' &&
      nextSceneState.judgeResult === null &&
      nextSceneState.diceRoll === null
    ) {
      setStoredStorySceneState({
        ...createEmptyStorySceneState(nextSceneNumber),
        maxHp: maxHp,
        currentHp: currentHp,
        items: sceneItems,
      })
    }

    setSearchParams({ scene: String(nextSceneNumber) })
  }

  const handlePreviousScene = () => {
    persistCurrentSceneState()

    if (currentSceneNumber === 1) {
      navigate('/background')
      return
    }

    setSearchParams({ scene: String(currentSceneNumber - 1) })
  }

  const handleRestart = () => {
    clearAllStoredGameData()
    navigate('/', { replace: true })
  }

  const modifier = judgeResult?.needs_roll ? getAbilityModifier(judgeResult.ability) : 0
  const displayRoll = diceRoll ?? (isRolling ? rollingValue : null)
  const totalRoll = displayRoll !== null ? displayRoll + modifier : null
  const isPlayerActionEmpty = playerAction.trim().length === 0
  const isConfirmActionDisabled = isJudgeLoading || isPlayerActionEmpty || !generatedScene
  const canAdvanceScene =
    generatedScene?.is_ending !== true &&
    judgeResult !== null &&
    (!judgeResult.needs_roll || diceRoll !== null)
  const nextButtonLabel = generatedScene?.next_is_ending ? 'エンディングへ' : '次へ'
  const difficulty = judgeResult?.difficulty ?? null
  const isSuccess =
    totalRoll !== null && difficulty !== null
      ? totalRoll >= difficulty
      : null

  return (
    <main className="page-shell px-4" data-theme="light">
      <PageHeader
        title={`シーン${currentSceneNumber}${generatedScene?.scene_title ? `：${generatedScene.scene_title}` : ''}`}
        backAction={{
          label: '戻る',
          onClick: handlePreviousScene,
          variant: 'outline',
        }}
        nextAction={{
          label: nextButtonLabel,
          onClick: handleNextScene,
          disabled: !canAdvanceScene,
          variant: 'primary',
        }}
        restartAction={{ label: '最初から', onClick: handleRestart, variant: 'error' }}
      />
      <section className="page-panel w-full max-w-[1240px] p-5">

        <div className="mt-4 grid grid-cols-[360px_minmax(0,1fr)] gap-4">
          <aside className="flex flex-col gap-5">
            <section className="card border border-base-300 bg-base-200/70">
              <div className="card-body p-4">
              <h2 className="font-[var(--heading-font)] text-2xl text-neutral">
                {selectedJob.name}
              </h2>
              <div className="mt-4">
                <div className="flex items-center justify-between gap-4">
                  <span className="text-sm uppercase tracking-[0.18em] text-base-content/60">HP</span>
                  <strong className="text-lg text-neutral">
                    {currentHp} / {maxHp}
                  </strong>
                </div>
                <progress
                  className="progress progress-error mt-2 w-full"
                  value={currentHp}
                  max={Math.max(maxHp, 1)}
                />
                <p className="mt-2 text-sm text-base-content/60">
                  残り {Math.round(hpRatio)}%
                </p>
              </div>
              <div className="mt-4 flex flex-col gap-2 text-base text-base-content">
                {abilityRows.map(([label, value]) => (
                  <div key={label} className="flex items-center justify-between gap-4">
                    <span className="text-base-content/60">{label}</span>
                    <strong className="text-neutral">{value}</strong>
                  </div>
                ))}
              </div>
              </div>
            </section>

            <section className="card border border-base-300 bg-base-200/70">
              <div className="card-body p-4">
              <h2 className="font-[var(--heading-font)] text-2xl text-neutral">
                選択したアイテム
              </h2>
              <p className="mt-2 text-base text-base-content/60">
                行動時に使うアイテムを選択してください。
              </p>
              <div className="mt-4 flex flex-col gap-3">
                {sceneItems.map((item) => (
                  <label
                    key={item.id}
                    className={[
                      'card grid cursor-pointer grid-cols-[20px_minmax(0,1fr)] gap-3 border p-3 transition',
                      availableActiveItemIds.includes(item.id)
                        ? 'border-primary bg-base-100'
                        : 'border-base-300 bg-base-100/75 hover:border-secondary hover:bg-base-100',
                    ].join(' ')}
                  >
                    <input
                      type="checkbox"
                      checked={availableActiveItemIds.includes(item.id)}
                      onChange={() => handleToggleActiveItem(item.id)}
                      className="checkbox checkbox-primary checkbox-sm mt-1"
                    />
                    <div>
                      <div className="flex items-baseline justify-between gap-4">
                        <strong className="text-base text-neutral">
                          {item.name}
                        </strong>
                        <span className="badge badge-outline border-base-300 px-3 py-2 text-sm text-base-content/70">
                          {item.category}
                        </span>
                      </div>
                      <p className="mt-2 text-base leading-7 text-base-content">
                        {item.description}
                      </p>
                    </div>
                  </label>
                ))}
              </div>
              </div>
            </section>
          </aside>

          <section className="card border border-base-300 bg-base-200/70">
            <div className="card-body p-5">
            {errorMessage ? (
              <p className="alert alert-error text-base">
                {errorMessage}
              </p>
            ) : null}
            <div className="card border border-base-300 bg-base-100/85">
              <div className="card-body p-4">
              {generatedScene ? (
                <div>
                  <h3 className="font-[var(--heading-font)] text-2xl text-neutral">
                    {generatedScene.scene_title}
                  </h3>
                  <p className="mt-3 whitespace-pre-wrap text-base leading-8 text-base-content">
                    {generatedScene.scene_text}
                  </p>
                  {generatedScene.is_ending ? (
                    <p className="mt-4 text-sm text-base-content/70">
                      このシーンで物語は決着しています。戻る から過去のシーンを見直せます。
                    </p>
                  ) : null}
                </div>
              ) : (
                <p className="text-base text-base-content">
                  シーンを生成しています。しばらく待つと、このシーンの状況が表示されます。
                </p>
              )}
              </div>
            </div>
            <div className="mt-4 flex justify-end">
              <button
                type="button"
                className="btn btn-primary disabled:opacity-50"
                onClick={handleGenerateScene}
                disabled={isSceneLoading}
              >
                {isSceneLoading ? '生成中...' : 'シーン再生成'}
              </button>
            </div>
            <div className="card mt-4 border border-base-300 bg-base-100/85">
              <div className="card-body p-4">
              <p className="text-base text-base-content/60">今回使うアイテム</p>
              {activeItems.length > 0 ? (
                <div className="mt-3 flex flex-wrap gap-2">
                  {activeItems.map((item) => (
                    <span
                      key={item.id}
                      className="badge badge-primary h-auto px-3 py-3 text-base"
                    >
                      {item.name}
                    </span>
                  ))}
                </div>
              ) : (
                <p className="mt-2 text-base text-base-content">
                  まだ選択されていません。
                </p>
              )}
              </div>
            </div>
            <div className="mt-4">
              <label
                htmlFor="player-action"
                className="text-base text-base-content/60"
              >
                ユーザー行動
              </label>
              <textarea
                id="player-action"
                value={playerAction}
                onChange={(event) => setPlayerAction(event.target.value)}
                placeholder="どう行動するか入力"
                className="textarea textarea-bordered mt-2 min-h-[140px] w-full bg-base-100 text-base leading-8 text-base-content placeholder:text-base-content/50"
              />
              <div className="mt-4 flex justify-end">
                <button
                  type="button"
                  className="btn btn-primary"
                  onClick={handleConfirmAction}
                  disabled={isConfirmActionDisabled}
                >
                  {isJudgeLoading ? '判定中...' : '行動を確定'}
                </button>
              </div>
            </div>
            {judgeResult ? (
              <div className="card mt-4 border border-base-300 bg-base-100/85">
                <div className="card-body p-4">
                <p className="text-base leading-8 text-base-content">
                  {judgeResult.message}
                </p>
                {judgeResult.needs_roll ? (
                  <div className="mt-3 flex flex-wrap gap-3 text-base text-base-content">
                    <span className="badge badge-outline h-auto border-base-300 px-3 py-2">
                      能力値: {judgeResult.ability}
                    </span>
                    <span className="badge badge-outline h-auto border-base-300 px-3 py-2">
                      技能: {judgeResult.skill}
                    </span>
                    <span className="badge badge-outline h-auto border-base-300 px-3 py-2">
                      難易度: {judgeResult.difficulty}
                    </span>
                  </div>
                ) : (
                  <p className="mt-3 text-base text-base-content/60">
                    判定不要
                  </p>
                )}
                </div>
              </div>
            ) : null}
            {judgeResult?.needs_roll ? (
              <div className="card mt-4 border border-base-300 bg-base-100/85">
                <div className="card-body p-4">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-base text-base-content/60">d20 判定</p>
                    <p className="mt-1 text-base text-base-content">
                      {judgeResult.ability
                        ? `${abilityLabels[judgeResult.ability as keyof typeof abilityLabels]}修正 ${modifier >= 0 ? `+${modifier}` : modifier}`
                        : '修正値 0'}
                    </p>
                  </div>
                  <div className="flex items-center gap-3">
                    {IS_DEV ? (
                      <button
                        type="button"
                        className="btn btn-outline"
                        onClick={handleRerollDice}
                        disabled={diceRoll === null}
                      >
                        振り直し
                      </button>
                    ) : null}
                    <button
                      type="button"
                      className="btn btn-primary disabled:opacity-50"
                      onClick={handleRollDice}
                      disabled={!isRolling}
                    >
                      決定
                    </button>
                  </div>
                </div>
                <div className="stats stats-vertical mt-4 grid grid-cols-5 gap-3 bg-transparent shadow-none lg:stats-horizontal">
                  <div className="stat rounded-2xl border border-primary bg-base-100 text-center">
                    <p className="stat-title text-base-content/60">出目</p>
                    <p className="stat-value mt-2 text-4xl font-bold leading-none text-neutral">
                      {displayRoll ?? '-'}
                    </p>
                  </div>
                  <div className="stat rounded-xl border border-base-300 bg-base-200/70">
                    <p className="stat-title text-base-content/60">修正値</p>
                    <p className="stat-value mt-1 text-lg font-semibold text-neutral">
                      {modifier >= 0 ? `+${modifier}` : modifier}
                    </p>
                  </div>
                  <div className="stat rounded-xl border border-base-300 bg-base-200/70">
                    <p className="stat-title text-base-content/60">合計</p>
                    <p className="stat-value mt-1 text-lg font-semibold text-neutral">
                      {totalRoll ?? '-'}
                    </p>
                  </div>
                  <div className="stat rounded-xl border border-base-300 bg-base-200/70">
                    <p className="stat-title text-base-content/60">目標値</p>
                    <p className="stat-value mt-1 text-lg font-semibold text-neutral">
                      {judgeResult.difficulty ?? '-'}
                    </p>
                  </div>
                  <div className="stat rounded-xl border border-base-300 bg-base-200/70">
                    <p className="stat-title text-base-content/60">結果</p>
                    <p className="stat-value mt-1 text-lg font-semibold text-neutral">
                      {isSuccess === null ? '-' : isSuccess ? '成功' : '失敗'}
                    </p>
                  </div>
                </div>
                {canAdvanceScene ? (
                  <div className="mt-4 flex justify-end">
                    <button
                      type="button"
                      className="btn btn-secondary"
                      onClick={handleNextScene}
                    >
                      {nextButtonLabel}
                    </button>
                  </div>
                ) : null}
                </div>
              </div>
            ) : null}
            </div>
          </section>
        </div>
      </section>
    </main>
  )
}
